FORMAT: 1A
HOST: http://api.shiftcommerce.com/#{app_name.gsub(/^shift_/,'')}/v1

# #{app_name.humanize}

Add a description here then read this (https://github.com/shiftcommerce/shift-inventory/wiki/Documenting-And-Testing-Using-API-Blueprint)
to get started.
